name: mpabot_reddit_parser

services:
  reddit-parser-web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=reddit-parser-backend:9090
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 100:100
    depends_on:
      - reddit-parser-backend
    networks:
      - subnet

  reddit-parser-backend:
    container_name: reddit-parser-backend
    image: reddit-parser-service_backend
    build:
      context: app
      target: builder
    # app requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9090
      - MONGO_URI=mongodb://reddit-parser-mongo:27017/reddit-parser_db
    volumes:
      - ./app:/src
    depends_on:
      - reddit-parser-mongo
    networks:
      - subnet
      - data-net

  reddit-parser-mongo:
    container_name: reddit-parser-mongo
    image: mongo
    ports:
      - 50003:27017
    volumes:
      - reddit-parser-data:/data/db
    networks:
      - subnet

networks:
  subnet:
    driver: bridge
  data-net:
    external:
      name: mpabot_data_controller_data-net

volumes:
  reddit-parser-data: