swagger: "2.0"
info:
  description: "This is a web parsing service designed for Reddit."
  version: "1.0.0"
  title: "Reddit Parser"
tags:
- name: "RESTful API"
paths:
  /search:
    post:
      tags:
        - "RESTful API"
      summary: "Ask for related Reddit website"
      description: "Search related information from Google search engine. Response url list."
      operationId: "searchRedditURL"
      consumes: "application/json"
      produces: "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Search for related Reddit comments"
          required: true
          schema:
            $ref: "#/definitions/SearchRequest"
      responses:
        400:
          description: Invalid input
        401:
          description: Unauthorized error
        200:
          description: Success
          schema:
            type: object
            required:
              - "result"
            properties:
              result:
                type: "array"
                items:
                  type: "string"
  /retrieve:
    post:
      tags:
        - "RESTful API"
      summary: "Parse full Reddit posts."
      description: "Retrieve full information of Reddit posts. Insert first-search posts into database."
      operationId: "retrieveReddit"
      consumes: "application/json"
      produces: "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Search for related Reddit comments"
          required: true
          schema:
            $ref: "#/definitions/SearchRequest"
      responses:
        400:
          description: Invalid input
        401:
          description: Unauthorized error
        200:
          description: Success
          schema:
            type: object
            required:
              - "result"
            properties:
              result:
                type: "array"
                items:
                  $ref: "#/definitions/RedditData"

definitions:
  SearchRequest:
    type: "object"
    required:
      - "keywords"
      - "result_num"
      - "page_num"
    properties:
      keywords:
        type: "array"
        items:
          type: "string"
        example:
          - "app"
          - "CORS"
          - "error"
      result_num:
        type: "integer"
        format: "int64"
        example: 5
      page_num:
        type: "integer"
        format: "int64"
        example: 0
  RedditData:
    type: "object"
    required:
      - "link"
      - "question"
      - "answers"
    properties:
      link:
        type: "string"
      question:
        type: "object"
        required:
          - "id"
          - "title"
          - "content"
        properties:
          id:
            type: "string"
          title:
            type: "string"
          content:
            type: "string"
      answers:
        type: "array"
        items:
          type: "object"
          required:
            - "id"
            - "vote"
            - "content"
            - "parent"
          properties:
            id:
              type: "string"
            vote:
              type: "integer"
              format: int64
            content:
              type: "string"
            parent:
              type: "string"
